env:
  browser: true
  commonjs: true
  es2021: true
  node: true
ignorePatterns:
  - data/tupa.js
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
rules: {}
overrides:
  - files:
      - '**/*.mjs'
    parserOptions:
      sourceType: module
